name: test

on:
  pull_request:
  push:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [windows-latest]

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: install nushell
        uses: taiki-e/install-action@v1
        with:
          tool: nu

      - name: cargo build
        run: |-
          echo -n 'BIN_PATH=' >> $GITHUB_ENV && 
          cargo build --message-format json |
          jq -r 'select(.target?.name == "nu_plugin_dns" and (.target?.kind | contains(["bin"]))) | .executable' >> $GITHUB_ENV

      - name: touch plugins.nu
        run: touch plugins.nu

      - name: test
        env:
          RUST_LOG: debug
        run: nu --plugin-config plugins.nu -c "register $BIN_PATH; dns query google.com"
